# Generated by Django 3.1.7 on 2021-02-22 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company_address',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company_country',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company_place',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company_size',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company_zipcode',
        ),
    ]
