# Generated by Django 3.1.7 on 2021-03-10 21:25

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='short_description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
