# Generated by Django 3.1.7 on 2021-03-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20210310_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
