# Generated by Django 3.1.7 on 2021-03-10 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20210310_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='short_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
