# Generated by Django 3.1.7 on 2021-02-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_auto_20210221_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='content',
            field=models.TextField(),
        ),
    ]
