# Generated by Django 3.1.7 on 2021-02-21 12:57

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_auto_20210221_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
