# Generated by Django 3.1.7 on 2021-02-21 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_auto_20210221_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='content',
            new_name='cover_letter',
        ),
    ]
