# Generated by Django 3.1.7 on 2021-02-21 13:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_auto_20210221_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cover_letter',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
