# Generated by Django 3.1.7 on 2021-02-21 14:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_auto_20210221_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='experience',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
