# Generated by Django 3.1.7 on 2021-02-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20210224_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='company_size',
            field=models.CharField(blank=True, choices=[('size_1-9', '1-9'), ('size_10-49', '10-49'), ('size_50-99', '50-99'), ('size_100', '100+')], max_length=20, null=True),
        ),
    ]
