# Generated by Django 3.1.7 on 2021-02-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20210224_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='person_sex',
            field=models.CharField(blank=True, choices=[('M', 'M'), ('F', 'F')], max_length=1, null=True),
        ),
    ]
