# Generated by Django 3.1.7 on 2021-02-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_auto_20210225_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
